### ISSUE TITLE
No support for optional named regex groups

### ISSUE THREAD

**Issue by jackluo923** [edvinv/named-js-regexp#1]
`var re = namedRegexp(/^(:<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) (:<severity>DEBUG|WARNING|TRACE|ERROR|) (:<component>[\w-.]+) \[-?(:<requestId>[\w-.]+)? ?(:<userId>[\w-.]+)? ?(:<projectId>[\w-.]+)?\]/);`
 `var result = re.exec(noneAnsiLine);`
 `result.groups();`

When optional field are missing, matched.groups inside named-js-regexp.js does not handle this case properly.

**Comment by edvinv** [comment]
I have checked your regex and it looks that it is correctly converted to JS regexp.

``` js
var noneAnsiLine = "";
var re = named(/^(:<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) (:<severity>DEBUG|WARNING|TRACE|ERROR|) (:<component>[\w-.]+) \[-?(:<requestId>[\w-.]+)? ?(:<userId>[\w-.]+)? ?(:<projectId>[\w-.]+)?\]/); 
console.log("Source:");
console.log(re.source);
console.log("Indices:");
console.log(re.groupsIndices);
```

Output is:

```
Source:
^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) (DEBUG|WARNING|TRACE|ERROR|) ([\w-.]+) \[-?([\w-.]+)? ?([\w-.]+)? ?([\w-.]+)?\]
Indices:
{ timestamp: 1,
  severity: 2,
  component: 3,
  requestId: 4,
  userId: 5,
  projectId: 6 }
```

So generated re.source looks OK. Can you also provide noneAnsiLine and expected result?

**Comment by jackluo923** [comment]
@edvinv Hi Edvin, the named-js-regexp npm library is free of any fault. I mixed up the documentation for a similar library called xregexp where it supports accessing regex groups simply via result.groupName directly after re.exec. The error is on me and sorry about the erroneous issues ticket.
