### ISSUE TITLE
Capture non-named groups

### ISSUE THREAD

**Issue by rektide** [edvinv/named-js-regexp#3]
For:
```
var njs = require('named-js-regexp')
var re = njs(/(:<hour>\d\d?):stuff:(and)/)
```

Currently I get `re` equal to `{hour: '12'}`. I'd like a way to still capture the unnamed parameter group `(and)` in that match, and get it's result. Presently the unnamed group seems to go missing.

**Comment by edvinv** [comment]
``` js
    var njs = require('named-js-regexp')
    var re = njs(/(:<hour>\d\d?):stuff:(and)/)
    var match = re.exec("12:stuff:and");
```

Now you can access unnamed groups:
`match => ["12:stuff:and", "12", "and"]`
So to access unnamed group (and):
`match[2] =>"and"`

To access named groups:
`match.groups() => {hour: "12"}`

Hope this helps.
